micronaut:
  application:
    name: DurkaFeedbackBot
  server:
    port: 8080
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

endpoints:
  prometheus:
    sensitive: false
  health:
    enabled: true
    sensitive: false

datasources:
  default:
    url: jdbc:postgresql://${DB}:${DBPORT:5432}/${DBNAME:durkafeedbackbot}
    username: ${DBUSER:durkafeedbackbot}
    password: ${DBPASS:sa}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true

bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}
  durkaChatId: ${DURKA_CHAT_ID}
  durkaLink: ${DURKA_LINK}
  durkaChannelId: ${DURKA_CHANNEL_ID}
