micronaut:
  application:
    name: DurkaFeedbackBot

mongodb:
  uri: ${MONGODB_URI}

username: ${username}
token: ${token}
durkaChatId: ${chat-id}
durkaLink: ${durka-link}
durkaChannelId: ${durka-channel-id}
