micronaut:
  application:
    name: DurkaFeedbackBot

datasources:
  default:
    url: jdbc:postgresql://${DB}:${DBPORT:5432}/${DBNAME:durkafeedbackbot}
    username: ${DBUSER:durkafeedbackbot}
    password: ${DBPASS:sa}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true

username: ${username}
token: ${token}
durkaChatId: ${chat-id}
durkaLink: ${durka-link}
durkaChannelId: ${durka-channel-id}
