spring:
  data:
    mongodb:
      uri: ${database}
      database: durkabot

logging:
  level:
    root: ERROR

username: ${username}
token: ${token}
durkaChatId: ${chat_id}
durkalink: ${durka_link}
durkaChannelId: ${durka_channel_id}
