micronaut:
  application:
    name: DurkaFeedbackBot

datasources:
  default:
    url: jdbc:h2:${DB:`mem:durkafeedback`};LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: ${DBUSER:sa}
    password: ${DBPASS:sa}
    driver-class-name: org.h2.Driver
    schema-generate: NONE
    dialect: H2

flyway:
  datasources:
    default:
      enabled: true


username: ${username}
token: ${token}
durkaChatId: ${chat-id}
durkaLink: ${durka-link}
durkaChannelId: ${durka-channel-id}
